const Discord = require('discord.js');
const superagent = require('superagent');


module.exports = {
    name: "animal",
    description: "Permet de lié un membre a un animal.",
    category: "fun",
    ownerOnly: false,
    fondateurOnly: false,
    userPerms: ["SendMessages"],
    botPerms: ["SendMessages"],
    options: [
        {
            type: Discord.ApplicationCommandOptionType.User,
            name: "membre",
            description: "Veuillez selectionner le membre.",
            required: false
        }
    ],

    async execute(interaction, client, db, emoji, color) {


        const member = interaction.options.getMember("membre") || interaction.member;

        const listAnimaux = [
            { name: 'Accenteur mouchet', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/accenteur-mouchet-photo-2.jpg'},
            { name: 'Addax', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/addax-photo-gallerie-2.jpg'},
            { name: 'Aigle royal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/aigle-royal-rapace.jpg'},
            { name: 'Aigrette garzette', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/Aigrette-garzette-photo-2.jpg'},
            { name: 'Alligator américain', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/Alligator-americain-photo-instinct-animal.jpg'},
            { name: 'Alouette des champs', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/alouette-des-champs-photos-2.jpg'},
            { name: 'Alpaga', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/Alpaga-photo-instinct-animal.jpeg'},
            { name: 'Anaconda géant', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/anaconda-geant-2.jpg'},
            { name: 'Anoa des plaines', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/Anoa-des-plaines-photo-instinct-animal.jpg'},
            { name: 'Antilope Cervicapre', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/antilope-cervicapre.jpg'},
            { name: 'Antilope de Clarke', image: 'https://i.skyrock.net/7367/68957367/pics/2750416208_1.jpg'},
            { name: 'Antilope du Tibet', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/04/antilope-du-tibet-photo-4-1.jpg'},
            { name: 'Antilope Nilgaut', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/antilope-nilgaut-photo-instinct-animal-2.jpg'},
            { name: 'Antilope Rouanne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/antilope-rouanne.jpg'},
            { name: 'Antilope Saiga', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/antilope-saiga-photo-instinct-animal-2.jpg'},
            { name: 'Ara bleu', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/ara-bleu-et-jaune-perroquet.jpg'},
            { name: 'Argali', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/argali.jpg'},
            { name: 'Autour des palombes', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/autour-des-palombes-rapace.jpg'},
            { name: 'Autruche d’Afrique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/autruche-afrique-male.jpg'},
            { name: 'Avocette élégante', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/avocette-elegante.jpg'},
            { name: 'Babiroussa', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/Babiroussa-photo-instinct-animal.jpg'},
            { name: 'Babouin Chacma', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/babouin-chacma-2-photo-instinct-animal.jpg'},
            { name: 'Babouin de Guinée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/babouin-de-guine%CC%81e-photo-instinct-animal.jpg'},
            { name: 'Babouin Hamadryas', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/babouin-hamadryas-photo-instinct-animal.jpg'},
            { name: 'Babouin jaune', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/babouin-jaune-photo-instinct-animal.jpg'},
            { name: 'Babouin olive', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/babouin-olive-photo-instinct-animal.jpg'},
            { name: 'Baleine bleue (Rorqual bleu)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/baleine-bleue-photo-instinct-animal.jpg'},
            { name: 'Banteng', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/banteng-photo-instinct-animal.jpg'},
            { name: 'Beira', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/beira-photo-instinct-animal-3.jpg'},
            { name: 'Belette d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/belette-europe-photo-instinct-animal-4.jpg'},
            { name: 'Bergeronnette grise', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/bergeronnette-grise-photo.jpg'},
            { name: 'Bernache du Canada', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/bernache-du-canada.jpg'},
            { name: 'Bison d’Amérique du Nord', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/bison-americain-photo-instinct-animal.jpg'},
            { name: 'Bison d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/bison-europe-photo-instinct-animal-2.jpg'},
            { name: 'Blaireau européen', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/blaireau-europe%CC%81en-photo-instinct-animal.jpg'},
            { name: 'Blesbok (Damalisque)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/blesbok-photo-instinct-animal.jpg'},
            { name: 'Boa constricteur', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/boa-constrictor-1.jpg'},
            { name: 'Boeuf musqué', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/boeuf-musque%CC%81-photo-instinct-animal.jpg'},
            { name: 'Bongo', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/bongo-photo-instinct-animal.jpg'},
            { name: 'Bonobo', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/bonobo-photo-instinct-animal.jpg'},
            { name: 'Bouquetin d’Abyssinie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/bouquetin-dAbyssinie-photo-instinct-animal.jpg'},
            { name: 'Bouquetin de Nubie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/bouquetin-de-nubie-photo-instinct-animal-2.jpg'},
            { name: 'Bouquetin de Sibérie (Yanghir)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/bouquetin-de-sibe%CC%81rie-photo-instinct-animal.jpg'},
            { name: 'Bouvreuil pivoine', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/bouvreuil-pivoine-photo.jpg'},
            { name: 'Bruant jaune', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/bruant-jaune-photo-2.jpg'},
            { name: 'Bruant ortolan', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/bruant-ortolan-2.jpg'},
            { name: 'Bubale roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/bubale-roux-photo-instinct-animal.jpg'},
            { name: 'Buffle d’Afrique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/buffle-Afrique-photo-instinct-animal.jpg'},
            { name: 'Buffle d’Asie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/buffle-asie-photo-instinct-animal-4.jpg'},
            { name: 'Busard Saint-Martin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/busard-saint-martin.jpg'},
            { name: 'Buse variable', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/buse-variable-photo-instinct-animal-2.jpg'},
            { name: 'Cacatoès rosalbin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/cacatoes-rosalbin-2.jpg'},
            { name: 'Caille des blés', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/caille-des-bles-2.jpg'},
            { name: 'Caïman noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/caiman-noir-photo-instinct-animal.jpg'},
            { name: 'Calopsitte élégante', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/calopsitte-e%CC%81le%CC%81gante-perruche.jpg'},
            { name: 'Campagnol des champs', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/campagnol-des-champs-1.jpg'},
            { name: 'Canard colvert', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/canard-colvert-sauvage-male-vol.jpg'},
            { name: 'Canard mandarin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/canard-mandarin-male.jpg'},
            { name: 'Canard siffleur', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/canard-siffleur.jpg'},
            { name: 'Capucin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/capucin-photo-instinct-animal.jpg'},
            { name: 'Capucin brun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/capucin-brun-photo-instinct-animal.jpg'},
            { name: 'Capybara', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/capybara-photo-instinct-animal-2.jpg'},
            { name: 'Caracal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/caracal-photo-instinct-animal-3.jpg'},
            { name: 'Carcajou', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/glouton-photo-3.jpg'},
            { name: 'Caribou', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/renne-caribou-2.jpg'},
            { name: 'Casoar à casque', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/casoar-a-casque.jpg'},
            { name: 'Castor d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/castor-europe-photo-instinct-animal.jpg'},
            { name: 'Castor du Canada', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/castor-du-canada-photo-instinc-animal.jpg'},
            { name: 'Céphalophe à dos jaune', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-a-dos-jaune-photo-instinct-animal.jpg'},
            { name: 'Céphalophe à flancs roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-a-flancs-roux-photo-instinct-animal.jpg'},
            { name: 'Céphalophe à front noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-a-front-noir-photo-instinct-animal.jpg'},
            { name: 'Céphalophe à ventre blanc', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Blue_duiker.jpg/800px-Blue_duiker.jpg'},
            { name: 'Céphalophe bleu', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-bleu.jpg'},
            { name: 'Céphalophe d’Ader', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-dader.jpg'},
            { name: 'Céphalophe de Natal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-de-natal-photo-instinct-animal-2.jpg'},
            { name: 'Céphalophe de Peter', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-de-peter-photo-instinct-animal.jpg'},
            { name: 'Céphalophe noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-noir-photo-instinct-animal.jpg'},
            { name: 'Céphalophe zèbre', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cephalophe-zebre-photo-instinct-animal.jpg'},
            { name: 'Cerf Axis', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/cerf-axis-photo-3.jpg'},
            { name: 'Cerf cochon', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cerf-cochon-photo-instinct-animal.jpg'},
            { name: 'Cerf élaphe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cerf-e%CC%81laphe-photo-instinct-animal.jpg'},
            { name: 'Chacal à chabraque', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/chacal-a-chabraque-photo-2.jpg'},
            { name: 'Chacal à flancs rayés', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chacal-a-flancs-rayes-photo-instinct-animal.jpg'},
            { name: 'Chacal doré (chacal commun)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/chacal-dore-photo-2.jpg'},
            { name: 'Chameau domestique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/chameau-de-bactriane-photo-2.jpg'},
            { name: 'Chameau sauvage de Tartarie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chameau-sauvage-photo-instinct-animal.jpg'},
            { name: 'Chamois', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chamois-photo-instinct-animal.jpg'},
            { name: 'Chardonneret élégant', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/04/chardonneret-elegant-photo.jpg'},
            { name: 'Chauve-souris pipistrelle commune', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/chauve-souris-pipistrelle-1.jpg'},
            { name: 'Chèvre des montagnes rocheuses', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/chevre-des-montagnes-rocheuses-photo-4.jpg'},
            { name: 'Chèvre du Caucase Occidental', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chevre-du-caucase-occidental-photo-instinct-animal.jpg'},
            { name: 'Chevreuil', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chevreuil-photo-instinct-animal.jpg'},
            { name: 'Chien chanteur de Nouvelle Guinée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chien-chanteur-de-nouvelle-guinee-photo-instinct-animal.jpeg'},
            { name: 'Chien des buissons', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chien-des-buissons-photo-instinct-animal.jpg'},
            { name: 'Chimpanzé commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/chimpanze%CC%81-photo-instinct-animal.jpg'},
            { name: 'Choucas des tours', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/choucas-des-tours-photo-2.jpg'},
            { name: 'Chouette chevêche d’Athéna', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/chouette-cheveche-athena-photo-3.jpg'},
            { name: 'Chouette effraie des clochers', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/chouette-effraie-des-clochers-photo.jpg'},
            { name: 'Chouette hulotte', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/chouette-hulotte-photo.jpg'},
            { name: 'Cigogne blanche', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/cigogne-blanche-photo.jpg'},
            { name: 'Civette africaine', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/civette-africaine-photo-instinct-animal.jpg'},
            { name: 'Coati commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/coati-photo-instinct-animal.jpg'},
            { name: 'Cobe à croissant', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cobe-a-croissant-photo-instinct-animal.jpg'},
            { name: 'Cobe de Buffon', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cobe-de-buffon-photo-instinct-animal.jpg'},
            { name: 'Cobe de Lechwe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/cobe-de-lechwe-photo-2.jpg'},
            { name: 'Cobe de Mrs Gray', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/cobe-de-mrs-gray-photo-instinct-animal.jpg'},
            { name: 'Cobra royal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/cobra-royal-1.jpg'},
            { name: 'Colibri circé', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/colibri-circe-oiseau-mouche.jpg'},
            { name: 'Condor des Andes', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/condor-des-andes-photo-instinct-animal.jpg'},
            { name: 'Corbeau freux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/corbeau-freux.jpg'},
            { name: 'Corneille noire', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/corneille-noire-photo.jpg'},
            { name: 'Coucou gris', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/coucou-gris-photo.jpg'},
            { name: 'Couleuvre à collier', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/12/couleuvre-a-collier-3.jpg'},
            { name: 'Coyote', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/coyote-photo-instinct-animal.jpg'},
            { name: 'Crocodile américain', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/crocodile-americain-photo-instinct-animal.jpg'},
            { name: 'Crocodile du Nil', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/crocodile-du-nil-photo-instinct-animal.jpg'},
            { name: 'Cygne noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/cygne-noir.jpg'},
            { name: 'Cygne tuberculé', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/cygne-tubercule%CC%81-nage.jpg'},
            { name: 'Daim', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/daim-male.jpg'},
            { name: 'Dauphin commun à bec court', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dauphin-commun-a-bec-court-photo-instinct-animal.jpg'},
            { name: 'Dhole', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/dhole-photo-4.jpg'},
            { name: 'Diable de Tasmanie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/diable-de-tasmanie.jpg'},
            { name: 'Dik-dik argenté', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dik-dik-argente-photo-instinct-animal.jpg'},
            { name: 'Dik-dik de Gunther', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dik-dik-de-gunther-photo-instinct-animal.jpg'},
            { name: 'Dik-dik de Kirk', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dik-dik-de-kirk-photo-instinct-animal.jpg'},
            { name: 'Dik-dik de Salt', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dik-dik-de-salt-photo-instinct-animal.png'},
            { name: 'Dingo', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dingo-photo-instinct-animal.jpg'},
            { name: 'Douc', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/douc-photo-instinct-animal.jpg'},
            { name: 'Dragon de Komodo', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/dragon-de-komodo-2.jpg'},
            { name: 'Drill', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/drill-photo-instinct-animal.jpg'},
            { name: 'Dromadaire', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/dromadaire-photo-instinct-animal.jpg'},
            { name: 'Dugong', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/dugong-2.jpg'},
            { name: 'Ecureuil roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/ecureuil-roux-branche.jpg'},
            { name: 'Elan d’Eurasie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/elan-eurasie-male.jpg'},
            { name: 'Eland de Derby', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/eland-de-derby-photo-instinct-animal.jpg'},
            { name: 'Eland du Cap', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/e%CC%81land-commun-photo-instinct-animal.jpg'},
            { name: 'Eléphant d’Afrique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/e%CC%81le%CC%81phant-afrique-photo-instinct-animal.jpg'},
            { name: 'Eléphant d’Asie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/e%CC%81le%CC%81phant-asie-photo-instinct-animal.jpg'},
            { name: 'Eléphant de mer du Sud', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/elephant-de-mer-du-sud-male.jpg'},
            { name: 'Emeu d’Australie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/emeu-australie.jpg'},
            { name: 'Engoulevent d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/engoulevent-europe-branche.jpg'},
            { name: 'Entelle', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/entelle-photo-instinct-animal.jpg'},
            { name: 'Entelle doré', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/entelle-dore%CC%81-langur-photo-instinct-animal.jpg'},
            { name: 'Epervier d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/epervier-europe-photo.jpg'},
            { name: 'Etourneau sansonnet', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/etourneau-sansonnet-photo.jpg'},
            { name: 'Faisan de Colchide', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/faisant-de-colchide-coq-photo-2.jpg'},
            { name: 'Faucon crécerelle', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/faucon-crecerelle-photo.jpg'},
            { name: 'Faucon pélerin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/faucon-pe%CC%81lerin-photo-instinct-animal.jpg'},
            { name: 'Fauvette à tête noire', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/fauvette-a-tete-noire-photo.jpg'},
            { name: 'Fennec', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/fennec-renard-du-desert.jpg'},
            { name: 'Flamant rose', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/flamant-rose-photo.jpg'},
            { name: 'Fossa', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/fossa-photo-instinct-animal.jpg'},
            { name: 'Fou de Bassan', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/fou-de-bassan-vol-photo.jpg'},
            { name: 'Fouine', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/fouine-photo-instinct-animal.jpg'},
            { name: 'Foulque macroule', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/foulque-macroule-photo-2.jpg'},
            { name: 'Fourmilier (tamanoir)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/tamanoir-fourmilier-geant-3.jpg'},
            { name: 'Furet', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/furet-photo-2.jpg'},
            { name: 'Gallinule poule-d’eau', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/gallinule-poule-d-eau-photo.jpg'},
            { name: 'Gaur (Gayal)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/gaur-gayal-photo-3.jpg'},
            { name: 'Gazelle à goître', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-a-goitre-photo-instinct-animal.jpg'},
            { name: 'Gazelle Dama', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/gazelle-de-dama-photo-2.jpg'},
            { name: 'Gazelle de Cuvier', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-cuvier-photo-instinct-animal.jpg'},
            { name: 'Gazelle de Grant', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-grant-photo-instinct-animal.jpg'},
            { name: 'Gazelle de montagne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-montagne-photo-instinct-animal.jpg'},
            { name: 'Gazelle de Rhim', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-rhim-photo-instinct-animal.jpg'},
            { name: 'Gazelle de Sommering', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-sommering-photo-instinct-animal.jpg'},
            { name: 'Gazelle de Speke', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-speke-photo-instinct-animal.jpg'},
            { name: 'Gazelle de Thomson', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-thomson-photo-instinct-animal.jpg'},
            { name: 'Gazelle de Waller', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-de-waller-photo-instinct-animal.jpg'},
            { name: 'Gazelle Dorcas', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-dorcas-photo-instinct-animal.jpg'},
            { name: 'Gazelle indienne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gazelle-indienne-photo-instinct-animal.jpg'},
            { name: 'Geai bleu', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/geai-bleu.jpg'},
            { name: 'Geai des chênes', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/geai-des-chenes-photo-instinct-animal.jpg'},
            { name: 'Gelada', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/ge%CC%81lada-photo-instinct-animal.jpg'},
            { name: 'Genette commune', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/genette-commune-photo-instinct-animal.jpg'},
            { name: 'Gibbon à favoris blancs du Nord', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-a-favoris-blancs-du-nord.jpg'},
            { name: 'Gibbon à joues jaunes', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-a%CC%80-joues-jaunes-photo-instinct-animal.jpg'},
            { name: 'Gibbon à mains blanches', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-a%CC%80-mains-blanches-photo-instinct-animal-2.jpg'},
            { name: 'Gibbon agile', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/gibbon-agile-photo-2.jpg'},
            { name: 'Gibbon de Hainan', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-de-hainan-photo-instinct-animal.jpeg'},
            { name: 'Gibbon Hoolock Occidental', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-hoolock-occidental-photo-instinct-animal.jpg'},
            { name: 'Gibbon noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/gibbon-noir-photo-2.jpg'},
            { name: 'Gibbon à bonnet', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-a-bonnet-photo-instinct-animal.jpg'},
            { name: 'Gibbon cendré', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-cendre-photo-instinct-animal.jpg'},
            { name: 'Gibbon de Muller', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gibbon-de-muller-photo-instinct-animal.jpg'},
            { name: 'Girafe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/girafe-photo-instinct-animal-2.jpg'},
            { name: 'Glouton', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/glouton-photo-3.jpg'},
            { name: 'Gnou bleu', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gnou-bleu-photo-instinct-animal.jpg'},
            { name: 'Gnou noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gnou-noir-photo-instinct-animal-2.jpg'},
            { name: 'Goéland argenté', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/goeland-argente-photo-2.jpg'},
            { name: 'Goral à longue queue', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/goral-a-longue-queue-photo-instinct-animal.jpg'},
            { name: 'Goral de l’Himalaya', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/goral-himalaya-photo-instinct-animal.jpg'},
            { name: 'Goral roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/goral-roux-photo-instinct-animal.jpg'},
            { name: 'Gorille de l’Est', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gorille-est-photo-instinct-animal.jpg'},
            { name: 'Gorille de l’Ouest', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/gorille-ouest-photo-instinct-animal.jpg'},
            { name: 'Grand bharal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/grand-bharal-photo-instinct-animal.jpg'},
            { name: 'Grand cachalot', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/grand-cachalot-photo-instinct-animal.jpg'},
            { name: 'Grand corbeau', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/grand-corbeau-photo.jpg'},
            { name: 'Grand cormoran', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/grand-cormoran-photo.jpg'},
            { name: 'Grand koudou', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/grand-koudou-photo-instinct-animal.jpg'},
            { name: 'Grand requin blanc', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/grand-requin-blanc-photo-instinct-animal.jpg'},
            { name: 'Grand requin marteau', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/grand-requin-marteau-photo-instinct-animal.jpg'},
            { name: 'Grand tétras', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/grand-tetras-coq-bruyere.jpg'},
            { name: 'Grande aigrette (héron blanc)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/grande-aigrette-heron-blanc.jpg'},
            { name: 'Grèbe huppé', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/grebe-huppe-photo.jpg'},
            { name: 'Grimpereau des jardins', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/grimpereau-des-jardins.jpg'},
            { name: 'Grison', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/grison-photo-instinct-animal.jpg'},
            { name: 'Grive musicienne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/grive-musicienne-photo.jpg'},
            { name: 'Grizzli', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/grizzly.jpg'},
            { name: 'Grue cendrée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/grue-cendree-vol-photo.jpg'},
            { name: 'Grosbec casse-noyaux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/grosbec-casse-noyaux-photo.jpg'},
            { name: 'Guanaco', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/guanaco-photo-instinct-animal.jpg'},
            { name: 'Guépard', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/guepard-photo-instinct-animal-2.jpg'},
            { name: 'Guêpier d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/guepier-europe-photo.jpg'},
            { name: 'Guib harnaché', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/guib-harnache-photo-instinct-animal.jpgs'},
            { name: 'Gypaète barbu', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/gypaete-barbu.jpg'},
            { name: 'Hamster d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/hamster-europe-2.jpg'},
            { name: 'Harfang des neiges', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/harfang-des-neiges-femelle.jpg'},
            { name: 'Hérisson commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/herisson-3.jpg'},
            { name: 'Hermine', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/Hermine-photo-instinct-animal.jpg'},
            { name: 'Héron cendré', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/heron-cendre-photo-2.jpg'},
            { name: 'Héron garde-boeufs', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/heron-garde-boeuf.jpg'},
            { name: 'Hibou Grand-duc d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/hibou-grand-duc-europe-photo.jpg'},
            { name: 'Hibou moyen-duc', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/hibou-moyen-duc.jpg'},
            { name: 'Hippopotame commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/hippopotame-photo-2.jpg'},
            { name: 'Hippotrague noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/hippotrague-noir-photo-4.jpg'},
            { name: 'Hirondelle rustique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/hirondelle-rustique.jpg'},
            { name: 'Huppe fasciée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/huppe-fasciee-photo.jpg'},
            { name: 'Hyène tâchetée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/hye%CC%80ne-tachete%CC%81e-photo-instinct-animal.jpg'},
            { name: 'Ibis sacré', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/ibis-sacre%CC%81.jpg'},
            { name: 'Impala', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/impala-photo-instinct-animal.jpg'},
            { name: 'Isard', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/isard-photo-instinct-animal.jpg'},
            { name: 'Jaguar', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/jaguar-photo-instinct-animal-2.jpg'},
            { name: 'Kangourou roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/kangourou-roux-1.jpg'},
            { name: 'Kiwi austral', image: 'https://lemagdesanimaux.ouest-france.fr/images/dossiers/2021-08/kiwi-autral-114742.jpg'},
            { name: 'Koala', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/koala-2.jpg'},
            { name: 'Lama', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/lama-photo-4.jpg'},
            { name: 'Lamantin des Caraïbes', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/lamantin-2.jpg'},
            { name: 'Langur à capuchon', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/langur-a-capuchon-photo-instinct-animal.jpeg'},
            { name: 'Langur de Delacour', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Langur-de-Delacour.jpg'},
            { name: 'Langur de Java', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/langur-de-java-photo.jpg'},
            { name: 'Lapin de garenne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/lapin-de-garenne-2.jpg'},
            { name: 'Lemming commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/lemming-commun-1.jpg'},
            { name: 'Léopard', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/leopard-photo-instinct-animal.jpg'},
            { name: 'Léopard des neiges', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/le%CC%81opard-des-neiges-photo-instinct-animal.jpg'},
            { name: 'Lièvre d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/lievre-europe-2.jpg'},
            { name: 'Linotte mélodieuse', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/linotte-melodieuse-male-photo.jpg'},
            { name: 'Lion blanc', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/lion-blanc-photo-2.jpg'},
            { name: 'Lion d’Afrique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2020/01/lion-afrique.jpg'},
            { name: 'Lion d’Asie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/lion-asie-photo-2.jpg'},
            { name: 'Lion de mer de Californie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/lion-de-mer-de-californie-2.jpg'},
            { name: 'Loriot d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/loriot-d-europe-male-photo.jpg'},
            { name: 'Loup arctique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/loup-arctique-photo-instinct-animal.jpg'},
            { name: 'Loup de Sibérie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/loup-de-siberie-photo-instinct-animal.jpg'},
            { name: 'Loup gris commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/loup-gris-commun-photo-instinct-animal.jpg'},
            { name: 'Loutre d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/loutre-europe-photo-instinct-animal.jpg'},
            { name: 'Loutre de mer', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/loutre-de-mer-photo-instinct-animal.jpg'},
            { name: 'Lycaon', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/lycaon-photo-instinct-animal.jpg'},
            { name: 'Lynx', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/lynx-commun-photo-instinct-animal.jpg'},
            { name: 'Macaque commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/macaque-commun-photo-instinct-animal.jpeg'},
            { name: 'Macareux moine', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/macareux-moine-photo-3.jpg'},
            { name: 'Maki catta', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/maki-catta-lemurien-1.jpg'},
            { name: 'Manchot empereur', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/Manchots-empereurs-1.jpg'},
            { name: 'Mandrill', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mandrill-photo-instinct-animal.jpg'},
            { name: 'Mangabey couronné', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mangabey-couronne-photo-instinct-animal.jpg'},
            { name: 'Mangabey noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mangabey-noir-photo-instinct-animal.jpg'},
            { name: 'Mangouste à queue blanche', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mangouste-a-queue-blanche-photo-instinct-animal.jpg'},
            { name: 'Mangouste rouge', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mangouste-rouge-photo-instinct-animal.jpg'},
            { name: 'Mara de Patagonie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mara-de-patagonie-photo-instinct-animal.jpg'},
            { name: 'Marabout d’Afrique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/marabout-afrique-2.jpg'},
            { name: 'Markhor', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/markhor-photo-instinct-animal.jpg'},
            { name: 'Marmotte des Alpes', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/marmotte-des-alpes-1.jpg'},
            { name: 'Marsouin commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/marsouin-commun-3.jpg'},
            { name: 'Martin pêcheur d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/martin-pecheur-europe-photo.jpg'},
            { name: 'Martinet noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/martinet-noir-photo-instinct-animal.jpg'},
            { name: 'Martre des pins', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/martre-des-pins-photo-instinct-animal.jpg'},
            { name: 'Merle noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/merle-noir-male-photo.jpg'},
            { name: 'Mésange à longue queue', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/mesange-a-longue-queue-photo.jpg'},
            { name: 'Mésange bleue', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/mesange-bleue-photo.jpg'},
            { name: 'Mésange charbonnière', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/mesange-charbonniere-male-photo.jpg'},
            { name: 'Mésange huppée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/mesange-huppee-photo.jpg'},
            { name: 'Mésange noire', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/mesange-noire-photo.jpg'},
            { name: 'Mésange nonnette', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/mesange-nonnette-photo-2.jpg'},
            { name: 'Milan noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/milan-noir-photo-instinct-animal.jpg'},
            { name: 'Milan royal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/milan-royal-rapace.jpg'},
            { name: 'Moineau domestique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/moineau-domestique-photo.jpg'},
            { name: 'Morse', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/morse-3.jpg'},
            { name: 'Mouffette rayée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/mouffette-raye%CC%81e-photo-instinct-animal.jpg'},
            { name: 'Mulot sylvestre', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/mulot-sylvestre-2.jpg'},
            { name: 'Musaraigne carrelet (commune)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/musaraigne-commune-1.jpg'},
            { name: 'Narval', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/narval-1.jpg'},
            { name: 'Nasique', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/nasique-photo-instinct-animal.jpg'},
            { name: 'Nasique des îles de Pagai', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/nasique-des-iles-pagai-photo-instinct-animal.jpg'},
            { name: 'Nyala', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Nyala-male-photo-instinct-animal.jpg'},
            { name: 'Nyala de montagne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/nyala-de-montagne-photo-instinct-animal.jpg'},
            { name: 'Ocelot', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/ocelot-photo-3.jpg'},
            { name: 'Oie cendrée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/oie-cendree-.jpg'},
            { name: 'Okapi', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/okapi-animal-afrique.jpg'},
            { name: 'Orang-outan de Bornéo', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/orang-outan-borneo.jpg'},
            { name: 'Orang-outan de Sumatra', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Orang-outan-de-Sumatra-photo-instinct-animal.jpg'},
            { name: 'Orignal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/orignal-male.jpg'},
            { name: 'Ornithorynque', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/ornithorynque-1.jpg'},
            { name: 'Orque', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/orque-epaulard.jpg'},
            { name: 'Orvet commun (fragile)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/12/orvet-commun-fragile-4.jpg'},
            { name: 'Oryx algazelle (blanc)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/oryx-algazelle-photo-instinct-animal.jpg'},
            { name: 'Oryx Beisa (d’Afrique de l’Est)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/oryx-beisa-photo-instinct-animal.jpg'},
            { name: 'Oryx d’Arabie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/oryx-arabie-photo-3.jpg'},
            { name: 'Oryx gazelle', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/oryx.jpg'},
            { name: 'Otarie de Kerguelen', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/otaries-de-kerguelen-3.jpg'},
            { name: 'Otocyon', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/otocyon-photo-instinct-animal.jpg'},
            { name: 'Ouistiti à toupets blancs', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/ouistiti-a-toupets-blancs-1.jpg'},
            { name: 'Ours brun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/ours-brun-photo-instinct-animal.jpg'},
            { name: 'Ours kodiak', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/ours-kodiac-1.jpg'},
            { name: 'Ours polaire', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/ours-polaire-photo-instinct-animal.jpg'},
            { name: 'Outarde canepetière', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/outarde-canepetiere-male-photo.jpg'},
            { name: 'Palombe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/pigeon-ramier-palombe-photo.jpg'},
            { name: 'Panda géant', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/panda-geant-photo-instinct-animal-2.jpg'},
            { name: 'Panda roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/panda-roux-photo-instinct-animal.jpg'},
            { name: 'Pangolin géant', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/pangolin-geant-1.jpg'},
            { name: 'Paon bleu', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/paon-bleu-male-roue-2.jpg'},
            { name: 'Paresseux à 2 doigts (unau)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/paresseux-unau-1.jpg'},
            { name: 'Pélican blanc', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/pelican-blanc-1.jpg'},
            { name: 'Perdrix grise', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/perdrix-grise-photo.jpg'},
            { name: 'Perdrix rouge', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/perdrix-rouge-photo-3.jpg'},
            { name: 'Perruche à collier', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/perruche-a-collier.jpg'},
            { name: 'Perruche ondulée', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/perruche-ondulee.jpg'},
            { name: 'Petit Bharal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/petit-bharal-photo-instinct-animal.jpg'},
            { name: 'Petit-duc scops (Hibou petit-duc)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/Petit-duc-scops-nuit.jpg'},
            { name: 'Petit Koudou', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/petit-koudou-photo-instinct-animal.jpg'},
            { name: 'Phacochère commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/phacochere.jpg'},
            { name: 'Phoque veau marin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/phoque-veau-marin-1.jpg'},
            { name: 'Pic épeiche', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/pic-epeiche-photo-instinct-animal.jpg'},
            { name: 'Pic vert', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/pic-vert-photo.jpg'},
            { name: 'Pie bavarde', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/pie-bavarde-photo.jpg'},
            { name: 'Pigeon ramier', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/pigeon-ramier-palombe-photo.jpg'},
            { name: 'Pingouin torda', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/04/pingouin-torda-photo.jpg'},
            { name: 'Pinson des arbres', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/pinson-des-arbres-male-photo.jpg'},
            { name: 'Porc-épic à crête', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/porc-epic-a-crete-2.jpg'},
            { name: 'Potamochère du Cap', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/potamochere-du-cap-2.jpg'},
            { name: 'Puku', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/puku-photo-instinct-animal.jpg'},
            { name: 'Puma', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/puma-photo-instinct-animal.jpg'},
            { name: 'Putois d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/putois-europe-2.jpg'},
            { name: 'Pygargue à tête blanche', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/pygargue-a-tete-blanche.jpg'},
            { name: 'Python de Seba', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/python-de-seba-1.jpeg'},
            { name: 'Python réticulé', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/python-reticule-1.jpg'},
            { name: 'Python royal', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/python-royal-2.jpg'},
            { name: 'Ragondin', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/ragondin-2.jpg'},
            { name: 'Raphicère (Steenbok)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/raciphere-steenbok-photo-1.jpg'},
            { name: 'Rat musqué', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/rat-musque-4.jpg'},
            { name: 'Ratel (Zorille du Cap)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/ratel-zorille-du-cap-photo-instinct-animal.jpg'},
            { name: 'Raton laveur commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/raton-laveur-photo-instinct-animal.jpg'},
            { name: 'Renard polaire', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/07/renard-des-neiges.jpg'},
            { name: 'Renard roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/renard-roux-photo-instinct-animal.jpg'},
            { name: 'Renne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/renne-caribou-2.jpg'},
            { name: 'Requin baleine', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/requin-baleine-photo-instinct-animal-2.jpg'},
            { name: 'Requin bouledogue', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/requin-bouledogue-photo-instinct-animal.jpg'},
            { name: 'Requin tigre', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/requin-tigre-photo-instinct-animal.jpg'},
            { name: 'Rorqual commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/baleine-bleue-photo-instinct-animal.jpg'},
            { name: 'Rhinocéros blanc', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/rhinoceros-blanc-photo-instinct-animal.jpg'},
            { name: 'Rhinocéros noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Rhinoceros-noir-photo-instinct-animal.jpg'},
            { name: 'Roitelet huppé', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/roitelet-huppe-photo.jpg'},
            { name: 'Rossignol philomèle', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/rossignol-philomele-photo.jpg'},
            { name: 'Rouge-gorge familier', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/04/rouge-gorge-familier-photo-1.jpg'},
            { name: 'Rougequeue noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/rougequeue-noir-photo-2.jpg'},
            { name: 'Sanglier', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Sanglier-photo-instinct-animal.jpg'},
            { name: 'Sarcelle d’hiver', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/sarcelle-hiver-envol.jpg'},
            { name: 'Sassabi', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/sassabi-photo-instinct-animal.jpg'},
            { name: 'Serin cini', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/serin-cini-male-photo-2.jpg'},
            { name: 'Serval', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Serval-photo-instinct-animal.jpg'},
            { name: 'Siamang', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/siamang-photo-1.jpg'},
            { name: 'Siamang de Kloss', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/siamang-de-kloss-photo-1.jpg'},
            { name: 'Singe araignée à tête brune', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-araignee-a-tete-brune-photo-1.jpg'},
            { name: 'Singe araignée aux mains noires', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-araignee-aux-mains-noires-photo-1.jpg'},
            { name: 'Singe araignée commun', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-araignee-commun-photo-1.jpg'},
            { name: 'Singe hurleur', image: 'https://www.sciencesetavenir.fr/assets/img/2015/10/23/cover-r4x3w1000-57e1726d7639e-singe-hurleur-en-foret.jpg'},
            { name: 'Singe hurleur à manteau', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-hurleur-a-manteau-photo-1.jpg'},
            { name: 'Singe hurleur du Guatémala', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-hurleur-du-guatemala-photo-1.jpg'},
            { name: 'Singe hurleur noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-hurleur-noir-male-photo-2.jpg'},
            { name: 'Singe hurleur roux', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/singe-hurleur-roux-photo-1.jpg'},
            { name: 'Sitatunga', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/sitatunga-photo-1.jpg'},
            { name: 'Sittelle torchepot', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/sittelle-torchepot-photo.jpg'},
            { name: 'Spatule blanche', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/spatule-blanche.jpg'},
            { name: 'Springbok', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/springbok-photo-instinct-animal.jpg'},
            { name: 'Suricate', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/08/Suricate.jpg'},
            { name: 'Tamanoir (fourmilier)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/tamanoir-fourmilier-geant-3.jpg'},
            { name: 'Tamarin-lion doré', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/tamarin-lion-dore-3.jpg'},
            { name: 'Tapir malais', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/tapir-malais-1.jpg'},
            { name: 'Tarsier des Philippines', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/tarsier-des-philippines-1.jpg'},
            { name: 'Taupe d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/taupe-europe-mammifere.jpg'},
            { name: 'Tigre', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Tigre-photo-instinct-animal.jpg'},
            { name: 'Tigre de Sibérie', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Tigre-de-Siberie-photo-instinct-animal.jpg'},
            { name: 'Tigre du Bengale', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Tigre-du-Bengale-photo-instinct-animal.jpg'},
            { name: 'Topi', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/topi-photo-1.jpg'},
            { name: 'Tortue d’Hermann', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/tortue-hermann-3.jpg'},
            { name: 'Tortue géante des Galapagos', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/tortue-geante-galapagos-2.jpg'},
            { name: 'Tortue luth', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/tortue-luth-3.jpg'},
            { name: 'Toucan toco', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/toucan-toco.jpg'},
            { name: 'Tourterelle des bois', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/tourterelle-des-bois-photo.jpg'},
            { name: 'Tourterelle turque', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/09/tourterelle-turque-2.jpg'},
            { name: 'Unau (paresseux à 2 doigts)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/paresseux-unau-1.jpg'},
            { name: 'Urial', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/urial-photo-1.jpg'},
            { name: 'Urubu noir', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/urubu-noir-photo-1.jpg'},
            { name: 'Vanneau huppé', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/vanneau-huppe-photo-2.jpg'},
            { name: 'Varan de Gould', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/varan-de-gould-1.jpg'},
            { name: 'Varan du Nil', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/varan-du-nil-2.jpg'},
            { name: 'Vautour fauve', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/vautour-fauve-photo-1.jpg'},
            { name: 'Verdier d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/05/verdier-d-europe-photo.jpg'},
            { name: 'Vipère aspic', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/11/vipere-aspic-3.jpg'},
            { name: 'Vigogne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/vigogne-photo-1.jpg'},
            { name: 'Vison d’Europe', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Vison-europe-photo-instinct-animal.jpg'},
            { name: 'Wallaby de Bennett (à cou rouge)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/wallaby-de-bennett-2.jpg'},
            { name: 'Wapiti', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Wapiti-photo-instinct-animal.jpg'},
            { name: 'Wombat', image: 'https://www.instinct-animal.fr/wp-content/uploads/2019/10/wombat-marsupial.jpg'},
            { name: 'Yak sauvage', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/yak-yack-photo-instinct-animal.jpg'},
            { name: 'Zèbre de Burchell', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Zebre-des-plaines-zebre-de-Burchell-photo-instinct-animal.jpg'},
            { name: 'Zèbre de Grevy', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Zebre-de-Grevy-photo-instinct-animal.jpg'},
            { name: 'Zèbre de montagne', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/Zebre-de-montagne-photo-instinct-animal.jpg'},
            { name: 'Zibeline', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/10/zibeline-photo-1.jpg'},
            { name: 'Zorille du Cap (Ratel)', image: 'https://www.instinct-animal.fr/wp-content/uploads/2018/09/ratel-zorille-du-cap-photo-instinct-animal.jpg'}
        ]

        const randomAnimal = listAnimaux[Math.floor(Math.random() * listAnimaux.length)]
        const animalName = randomAnimal.name;
        const animalImage = randomAnimal.image;

        const embed = new Discord.EmbedBuilder()
            .setColor(color)
            .setTitle(`${member.user.username} **est un ** \`${animalName}\``)
            .setImage(animalImage)
        interaction.reply({
            embeds: [embed]
        })
    }
}